Warehouse/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BLL.Interfaces;
using BLL.Models;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class AuthController : Controller
    {
        private IOperatorRepository _repository;
        public AuthController(IOperatorRepository operatorRepository)
        {
            _repository = operatorRepository;
        }

        public IActionResult LoginPage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginPage(AuthViewModel model)
        {
            if (model.UserName == "admin" && model.Password == "123")
            {
                //todo: logged as admin
                var principal = CreateAdmin();
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                return RedirectToAction("Index", "Admin");
            }

            var user = _repository.SignIn(model.UserName, model.Password);
            if (user != null)
            {
                // todo: logged as operator

                var principal = CreatePrincipal(user);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult NotAllowedPage()
        {
            return View();
        }

        private ClaimsPrincipal CreateAdmin()
        {
            var claims = new List<Claim>
            {
                new Claim("UserId", "0"),
                new Claim(ClaimTypes.Name, "Administrator"),
                new Claim(ClaimTypes.Role, "Admin")
            };
            var principal = new ClaimsPrincipal();
            principal.AddIdentity(new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme));
            return principal;
        }

        private ClaimsPrincipal CreatePrincipal(Operator user)
        {
            var claims = new List<Claim>
                {
                    new Claim("UserId", user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.UserName),
                    new Claim(ClaimTypes.Role, "Operator")
                };
            var principal = new ClaimsPrincipal();
            principal.AddIdentity(new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme));
            return principal;
        }
    }
}

Warehouse/Controllers/ClientController.cs
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class ClientController : Controller
    {
        private IClientRepository _repository;
        public ClientController(IClientRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var clients = _repository.GetAll();
            var viewModel = clients.Select(x=> new ClientViewModel(x.Id, x.Name));

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ClientViewModel model)
        {
            if (_repository.Exists(model.Name))
            {
                ViewBag.Error = "Такое имя уже существует";
                return View();
            }

            _repository.Create(model.Name);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Delete(decimal id)
        {
            if (_repository.Remove(id))
            {
                return new JsonResult(Ok());
            }

            return new JsonResult(BadRequest());
        }

        public IActionResult Edit(decimal id)
        {
            var client = _repository.Get(id);
            if (client == null)
            {
                return BadRequest();
            }
            return View(new ClientViewModel(client.Id, client.Name));
        }

        [HttpPost]
        public IActionResult Edit(ClientViewModel model)
        {
            if (_repository.Exists(model.Name))
            {
                ViewBag.Error = "такое имя уже существует";
                return View(model);
            }

            if (_repository.Rename(model.Id, model.Name))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Error = "что-то пошло не так, обратитесь в поддержку";
            return View(model);
        }
    }
}

Warehouse/Controllers/GoodsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL;
using BLL.Interfaces;
using BLL.Models;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class GoodsController : Controller
    {
        private IGoodsRepository _repository;
        public GoodsController(IGoodsRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var goods = _repository.GetAll();

            var viewModel = goods.Select(x=>new GoodsViewModel(x));

            return View(viewModel);
        }

        public IActionResult Edit(decimal id)
        {
            ViewData["GoodsCategories"] = _repository.GetGoodsCategories();
            ViewData["Dimensions"] = _repository.GetDimensions();
            var providers = _repository.GetProviders().ToList();
            providers.Insert(0, new Item(null, "Выберите поставщика или оставьте пустым"));
            ViewData["Providers"] = providers;

            var goods = _repository.Get(id);
            if (goods == null)
                return BadRequest();
            return View(new GoodsViewModel(goods));
        }

        [HttpPost]
        public IActionResult Edit(GoodsViewModel model)
        {
            var goods = new Goods(model.Id, model.Idx, model.Name, model.GoodsCatId, model.DimensionId, model.ProviderId, model.Val, model.ValDelivered, model.Price, 
                model.Delivery, model.ImpPeriod, model.ImpTime, model.Weight, null, null, null, 0, 0);
            if (_repository.Update(goods))
            {
                return RedirectToAction("Index");
            }

            return BadRequest();
        }

        public IActionResult Create()
        {
            ViewData["GoodsCategories"] = _repository.GetGoodsCategories();
            ViewData["Dimensions"] = _repository.GetDimensions();
            var providers = _repository.GetProviders().ToList();
            providers.Insert(0, new Item(null, "Выберите поставщика или оставьте пустым"));
            ViewData["Providers"] = providers;
            return View();
        }

        [HttpPost]
        public IActionResult Create(GoodsViewModel model)
        {
            var goods = new Goods(0, model.Idx, model.Name, model.GoodsCatId, model.DimensionId, model.ProviderId,
                model.Val, model.ValDelivered, model.Price, model.Delivery,
                model.ImpPeriod, model.ImpTime, model.Weight, null, null, null, 0, 0);
            _repository.Create(goods);
            return RedirectToAction("Index");
        }
    }
}

Warehouse/Controllers/ProviderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Interfaces;
using BLL.Models;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class ProviderController : Controller
    {
        private IProviderRepo _repository;

        public ProviderController(IProviderRepo repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var providers = _repository.GetAll();
            var viewModel = providers.Select(x => new ProviderViewModel(x));
            return View(viewModel);
        }

        public IActionResult Edit(decimal id)
        {
            var provider = _repository.Get(id);
            if (provider == null)
                return BadRequest();
            var viewModel = new ProviderViewModel(provider);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(ProviderViewModel model)
        {
            var provider = new Provider(model.Id, model.Name, model.Address, model.Phone);
            if (_repository.Update(provider))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Error = "Сохранить не удалось";
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(decimal id)
        {
            if (_repository.Remove(id))
            {
                return Ok();
            }

            return BadRequest();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProviderViewModel model)
        {
            var provider = new Provider(0, model.Name, model.Address, model.Phone);
            if (_repository.Create(provider))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Error = "Не удалось создать поставщика, возможно поля дублируются";
            return View(model);
        }
    }
}

Warehouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Магазин товаров</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Товары</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (User.IsInRole("Operator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Клиенты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GoodsCategory" asp-action="Index">Категории</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Goods" asp-action="Index">Товары</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dimension" asp-action="Index">Ед. измерения</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Provider" asp-action="Index">Поставщики</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Leftovers" asp-action="Index">Остатки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SuppliersWithGoods" asp-action="Index">Поставщики с товарами</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FileWithGoods" asp-action="Index">Отчёт</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DecommLog" asp-action="Index">Ист. срок годности</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Админка</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a style="float: right" class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Выйти</a>
                    }
                    else
                    {
                        <a style="float: right" class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="LoginPage">Войти</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Магазин товаров - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика конфиденциальности</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>