Warehouse/Models/DimensionViewModel.cs
using BLL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Warehouse.Models
{
    public class DimensionViewModel
    {
        public DimensionViewModel()
        {
        }

        public DimensionViewModel(Dimension x)
        {
            Id = x.Id;
            Name = x.Name;
        }

        public string Name { get; set; }

        public decimal Id { get; set; }
    }
}

Warehouse/Controllers/DimensionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Interfaces;
using BLL.Models;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class DimensionController : Controller
    {
        private IDimensionRepo _repository;

        public DimensionController(IDimensionRepo repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var dimensions = _repository.GetAll();
            var viewModel = dimensions.Select(x => new DimensionViewModel(x));
            return View(viewModel);
        }

        public IActionResult Edit(decimal id)
        {
            var dimension = _repository.Get(id);
            if (dimension == null)
                return BadRequest();
            return View(new DimensionViewModel(dimension));
        }

        [HttpPost]
        public IActionResult Edit(DimensionViewModel model)
        {
            var dimension = new Dimension(model.Id, model.Name);
            if (_repository.Update(dimension))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Error = "Произошла ошибка, обратитесь в поддержку";
            return View(model);
        }
    }
}

Warehouse/Views/Dimension/Edit.cshtml
@model Warehouse.Models.DimensionViewModel

@{
    ViewBag.Title = "Изменить ед. измер";
    Layout = "_Layout";
}

<style>
    label {
        width: 50%
    }

    div {
        border-bottom: 1px solid black;
    }
</style>

<h2>Изменить ед. измер</h2>

<span style="color: red">@ViewBag.Error</span>

@using (Html.BeginForm("Edit", "Dimension", FormMethod.Post, new {id = Model.Id}))
{
    <div>
        <label for="Name">Имя</label>
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div>
        <button type="submit">Сохранить</button>
    </div>
}

Warehouse/Views/Dimension/Index.cshtml
@model System.Collections.Generic.IEnumerable<Warehouse.Models.DimensionViewModel>

@{
    ViewBag.Title = "Единицы измерений";
    Layout = "_Layout";
}

<h2>Единицы измерений</h2>

<table>
    <thead>
    <tr>
        <th>Имя</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var dimension in Model)
    {
        <tr>
            <td>@dimension.Name</td>
            <td><button onclick="Edit(@dimension.Id)">Переименовать</button></td>
        </tr>
    }
    </tbody>
</table>

<script>
    function Edit(id) {
        window.location.href = '@Url.Action("Edit", "Dimension")/' + id;
    }
</script>