Warehouse/Models/GoodsCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Warehouse.Models
{
    public class GoodsCategoryViewModel
    {
        public GoodsCategoryViewModel()
        {
        }

        public GoodsCategoryViewModel(decimal id, string name)
        {
            Id = id;
            Name = name;
        }

        public decimal Id { get; set; }
        public string Name { get; set; }
    }
}

Warehouse/Controllers/GoodsCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Interfaces;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class GoodsCategoryController : Controller
    {
        private IGoodsCategoryRepo _repository;

        public GoodsCategoryController(IGoodsCategoryRepo repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var categories = _repository.GetAll();
            var viewModel = categories.Select(x=>new GoodsCategoryViewModel(x.Id, x.Name));
            return View(viewModel);
        }

        public IActionResult Edit(decimal id)
        {
            var category = _repository.Get(id);
            return View(new GoodsCategoryViewModel(category.Id, category.Name));
        }

        [HttpPost]
        public IActionResult Edit(GoodsCategoryViewModel model)
        {
            if (_repository.Exists(model.Name))
            {
                ViewBag.Error = "Такое имя уже есть";
                return View(model);
            }

            if (_repository.Rename(model.Id, model.Name))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Error = "Произошла неизвестная ошибка, обратитесь в поддержку";
            return View(model);
        }

    }
}

Warehouse/Views/GoodsCategory/Edit.cshtml
@model GoodsCategoryViewModel

@{
    ViewBag.Title = "Изменение категории";
    Layout = "_Layout";
}

<h2>Изменение категории товаров</h2>

<span style="color: red">@ViewBag.Error</span>

@using (Html.BeginForm("Edit", "GoodsCategory", FormMethod.Post, new { id = Model.Id }))
{
<table>
    <thead>
    <tr>
        <th>Имя</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            @Html.TextBoxFor(m=>m.Name)
        </td>
    </tr>
    <tr>
        <td>
            <button type="submit">Сохранить</button>
        </td>
    </tr>
    </tbody>
</table>
}

Warehouse/Views/GoodsCategory/Index.cshtml
@model System.Collections.Generic.IEnumerable<Warehouse.Models.GoodsCategoryViewModel>

@{
    ViewBag.Title = "Список категорий";
    Layout = "_Layout";
}

<h2>Список категорий</h2>

<table>
    <thead>
    <tr>
        <th>Имя</th>
        <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var category in Model)
    {
        <tr>
            <td>@category.Name</td>
            <td>
                <button onclick="Edit(@category.Id)">Переименовать</button>
            </td>
        </tr>
    }
    </tbody>
</table>
<script>
    function Edit(id) {
        window.location.href = '@Url.Action("Edit", "GoodsCategory")/' + id;
    }
</script>